### ISSUE TITLE
Chat in Production Not Working

### ISSUE THREAD

**Issue by Akshay13811** [Stream-Line/moodle-mod_streamline#26]
The chat is currently not working in the production environment. This issue is of high priority. 

I've investigated the issue a bit and this is what ive found out

 $HStuList = null;
 $StuList = null;
 $stuval = bin2hex($USER->username);
 include 'Chat/DataPrep.php';
 include 'Chat/StartChat.php';

These lines are missing from BBB.php, adding them makes the chat display correctly, although the chat wont work,

I get persons id is null on the chat server when sending a message this is because stuval is null. When I echo the stuval in BBB.php then it comes up with some value but it is null in chat.php. Maybe this is cause the BBB.php file location has changed or something, not too sure..

Anyways I thought id add the stuval at the top of the chat.php just for debugging purposes, it sends a message and there is a hit on the node server but the message is never displayed inside the chat.

Maruti can u please look into this issue further.

**Comment by Cookiearecoolcookies** [comment]
Hey,

So I found the problem, the lines you stated above should actually be places within streamline_modules.html, which actually should be of type .php. 

regards,
Maruti.

**Comment by Brotality** [comment]
So is this done? Can it be closed?

**Comment by Akshay224** [comment]
Im assuming this can now be closed since the chat is working correctly in production.
