### ISSUE TITLE
Recording Message Overlays Quiz Dialog

### ISSUE THREAD

**Issue by Akshay224** [Stream-Line/moodle-mod_streamline#36]
The recording message displayed at the top of the streamline session does not fade out when the Quiz dialog is opened.

![image](https://cloud.githubusercontent.com/assets/7035118/10266514/954eec0a-6ab5-11e5-84c8-df8b854b03ad.png)

**Comment by Brotality** [comment]
Its fading away on Matt's system. Is it something on your end?

**Comment by Akshay224** [comment]
Sorry I have fixed that issue last night, so since Matt pulled my changes yesterday he probably has the fixed solution.

 It was simply the z-index of the div being too high. It has been lowered to 1030 to display over the moodle header and beneath the fading of the overlay.
