### ISSUE TITLE
Refreshing resubmit quiz

### ISSUE THREAD

**Issue by MattWMitchell** [Stream-Line/moodle-mod_streamline#38]
If I refresh the page of the meeting then I can resubmit the quiz.

**Comment by Brotality** [comment]
Have it check if the user has submitted already, if so then just display the results.

**Comment by Akshay224** [comment]
As per Alex's comment, I have created a check to determine if the user has previously submitted. Requires further testing before I push the update.

**Comment by Akshay224** [comment]
Tested and now closing.
